[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = false
optimizer_runs = 200
via_ir = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
"@aave/v3/=lib/aave-v3-core/contracts"]

[profile.default.fuzz]
#seed = 1

[profile.default.invariant]
#runs = 500
#depth = 4
#max_test_rejects = 1
